name: admu_recweek_app
description: The official recweek mobile application of Ateneo de Manila University

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  firebase_messaging: ^6.0.16
  alphabet_list_scroll_view: ^1.0.6
  flutter_slidable: ^0.5.4
  url_launcher: ^5.5.0
  fluttertoast: ^7.0.2
  modal_bottom_sheet: ^0.2.0+1
  device_preview: ^0.4.7
  auto_size_text: ^2.1.0
  cloud_firestore: ^0.13.7
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: '^0.7.5'
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  ios: true
  android: true
  image_path_ios: 'assets/images/logo.png'
  image_path_android: 'assets/images/logo.png'

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/bodies/coa/
    - assets/bodies/cop/
    - assets/bodies/lions/
    - assets/bodies/student-groups/
    - assets/bodies/sanggu/
    - assets/orgs/dsc/
    - assets/team/
    - assets/data/
    - assets/orgs/coa/ANALYSIS_AND_DISCOURSE/
    - assets/orgs/coa/BUSINESS_CLUSTER/
    - assets/orgs/coa/COP/
    - assets/orgs/coa/FAITH_FORMATION/
    - assets/orgs/coa/HEALTH_AND_ENVIRONMENT/
    - assets/orgs/coa/INTERCULTURAL_RELATIONS/
    - assets/orgs/coa/MEDIA_AND_CREATIVES_CLUSTER/
    - assets/orgs/coa/PERFORMING_ARTS_CLUSTER/
    - assets/orgs/coa/SCIENCE_AND_TECH/
    - assets/orgs/coa/SECTOR-BASED/
    - assets/orgs/coa/STUDENT_GROUPS/
    - assets/orgs/lions/logos/
    - assets/orgs/lions/covers/
    
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
    - family: Google Sans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular-v1.27.ttf